### ISSUE TITLE
wrong current limit return

### ISSUE THREAD

**Issue by iqtemo** [arduino-libraries/Arduino_BQ24195#45]
This should return 0.150f instead of 0.015f.

https://github.com/arduino-libraries/Arduino_BQ24195/blob/c7cb8e8b5e8c0a9d7b5dcac8e544ea127856b237/src/BQ24195.cpp#L387C20-L387C26

**Comment by per1234** [comment]
Hi @iqtemo. Thanks for taking the time to submit an issue.

I see we have another report about this at https://github.com/arduino-libraries/Arduino_BQ24195/issues/7.

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
