### ISSUE TITLE
wrong current limit set

### ISSUE THREAD

**Issue by ku3i** [arduino-libraries/Arduino_BQ24195#46]
This should be compared against 0.15f instead of 0.015f.

https://github.com/arduino-libraries/Arduino_BQ24195/blob/c7cb8e8b5e8c0a9d7b5dcac8e544ea127856b237/src/BQ24195.cpp#L344C19-L344C24

**Comment by per1234** [comment]
Hi @ku3i. Thanks for taking the time to submit an issue.

I see we have another report about this at https://github.com/arduino-libraries/Arduino_BQ24195/issues/7.

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
