### ISSUE TITLE
wrong compare value (enum instead of float constant)

### ISSUE THREAD

**Issue by ku3i** [arduino-libraries/Arduino_BQ24195#47]
This should be compared against 0.9f instead of the enum.

https://github.com/arduino-libraries/Arduino_BQ24195/blob/c7cb8e8b5e8c0a9d7b5dcac8e544ea127856b237/src/BQ24195.cpp#L350C20-L350C35

**Comment by per1234** [comment]
Hi @ku3i. Thanks for taking the time to submit an issue.

I see we have another report about this at https://github.com/arduino-libraries/Arduino_BQ24195/issues/7.

It is best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.

If you end up with additional information to share, feel free to comment in the other thread.
